name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.9"
          environment-file: environment.txt 
          activate-environment: myenv
          channels: conda-forge,defaults
          channel-priority: strict
          auto-update-conda: true
      
      - name: List Files in Directory
        run: ls -lah
     
      - name: Create Conda environment from IPTpy requirements
        run: conda env create -f ../environment.txt

      - name: Update Conda environment with docs requirements
        run: conda env update --name myenv --file docs/environment.txt 

      - name: Activate Conda environment
        run: echo "conda activate myenv" >> $GITHUB_ENV  

      - name: Install IPTpy from local source
        run: |
          conda activate myenv
          pip install -e . 

      - name: Build documentation
        run: |
          conda activate myenv
          cd docs
          make html

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
